apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l42a1azdl-go
  janus-idp.io/tekton: l42a1azdl-go
  backstage.io/kubernetes-id: l42a1azdl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l42a1azdl-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
